/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
China Speedup (china-speedup) — 源码见 https://github.com/notesynchelper/china-speedup
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PluginMarketPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/logger.ts
var isDev = (() => {
  try {
    return false;
  } catch {
    return false;
  }
})();
var _Logger = class {
  static setDevMode(devMode) {
    _Logger.dev = devMode;
  }
  static debug(...args) {
    if (_Logger.dev)
      console.debug(...args);
  }
  static warn(...args) {
    console.warn(...args);
  }
  static error(...args) {
    console.error(...args);
  }
};
var Logger = _Logger;
Logger.dev = isDev;
var log = (...args) => Logger.debug(...args);
var logError = (...args) => Logger.error(...args);

// src/build-config.ts
var enableAutoUpdate = (() => {
  try {
    return true;
  } catch {
    return true;
  }
})();
var BUILD_CONFIG = {
  ENABLE_AUTO_UPDATE: enableAutoUpdate
};

// src/types.ts
var DEFAULT_SETTINGS = {
  enableSpecialImports: true,
  enableDeeplink: true,
  enableSelfUpdate: true,
  customConfigUrl: "",
  lastFastestBase: ""
};

// src/registry.ts
var import_obsidian2 = require("obsidian");

// src/whitelist.ts
var PRODUCT_DOMAINS = [
  "notebooksyncer.com",
  // obsidian.notebooksyncer.com 等
  "bijitongbu.site",
  // relay-1/2、shoujidiannao、graph、www 等子域
  "notehelper.app",
  "clipfx.app",
  // getcontent / pic 等
  "onenotes.app"
];
function isAllowedHost(host) {
  if (!host)
    return false;
  const h = host.trim().toLowerCase();
  const bare = h.split(":")[0];
  if (!bare)
    return false;
  return PRODUCT_DOMAINS.some(
    (d) => bare === d || bare.endsWith("." + d)
  );
}
function isAllowedUrl(url) {
  let u;
  try {
    u = new URL(url);
  } catch {
    return false;
  }
  if (u.protocol !== "https:")
    return false;
  return isAllowedHost(u.hostname);
}

// src/relaySelector.ts
var import_obsidian = require("obsidian");
var BOOTSTRAP_RELAYS = [
  { id: "relay-1", base: "https://relay-1.bijitongbu.site" },
  { id: "relay-2", base: "https://relay-2.bijitongbu.site" }
];
var PROBE_PATH = "/plugin-market/health";
var PROBE_TIMEOUT_MS = 3e3;
var CACHE_TTL_MS = 60 * 60 * 1e3;
var FAILURE_THRESHOLD = 3;
var CACHE_KEY = "plugin-market-cn:relayCache";
var normalizeBase = (base) => base.replace(/\/+$/, "");
var relaysToBases = (relays) => {
  const src = relays && relays.length ? relays : BOOTSTRAP_RELAYS;
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const r of src) {
    if (r.enabled === false)
      continue;
    if (!r.base)
      continue;
    const b = normalizeBase(r.base);
    if (seen.has(b))
      continue;
    seen.add(b);
    out.push(b);
  }
  return out.length ? out : BOOTSTRAP_RELAYS.map((r) => normalizeBase(r.base));
};
var defaultStorage = {
  getItem(key) {
    try {
      return window.localStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem(key, value) {
    try {
      window.localStorage.setItem(key, value);
    } catch {
    }
  },
  removeItem(key) {
    try {
      window.localStorage.removeItem(key);
    } catch {
    }
  }
};
var defaultRequestFn = async (url) => {
  const resp = await (0, import_obsidian.requestUrl)({ url, method: "GET" });
  return { status: resp.status };
};
var defaultDeps = {
  requestFn: defaultRequestFn,
  storage: defaultStorage,
  now: () => Date.now(),
  timeoutMs: PROBE_TIMEOUT_MS
};
var withTimeout = (p, ms) => new Promise((resolve, reject) => {
  const timer = setTimeout(
    () => reject(new Error(`probe timeout ${ms}ms`)),
    ms
  );
  p.then(
    (v) => {
      clearTimeout(timer);
      resolve(v);
    },
    (e) => {
      clearTimeout(timer);
      reject(e);
    }
  );
});
var probeBase = async (base, deps = defaultDeps) => {
  const url = normalizeBase(base) + PROBE_PATH;
  const timeoutMs = deps.timeoutMs ?? PROBE_TIMEOUT_MS;
  const start = deps.now();
  try {
    const resp = await withTimeout(deps.requestFn(url), timeoutMs);
    const latencyMs = deps.now() - start;
    const ok = resp.status === 200;
    return { base, ok, latencyMs, error: ok ? void 0 : `status=${resp.status}` };
  } catch (err) {
    const latencyMs = deps.now() - start;
    return {
      base,
      ok: false,
      latencyMs,
      error: err instanceof Error ? err.message : String(err)
    };
  }
};
var raceProbe = async (bases, deps = defaultDeps) => {
  if (bases.length === 0)
    return null;
  return new Promise((resolve) => {
    let settled = false;
    let remaining = bases.length;
    const finish = (result) => {
      if (settled)
        return;
      settled = true;
      resolve(result);
    };
    bases.forEach((base) => {
      probeBase(base, deps).then(
        (r) => {
          if (r.ok) {
            finish(r);
            return;
          }
          remaining -= 1;
          if (remaining === 0)
            finish(null);
        },
        () => {
          remaining -= 1;
          if (remaining === 0)
            finish(null);
        }
      );
    });
  });
};
var readCache = (bases, deps) => {
  const raw = deps.storage.getItem(CACHE_KEY);
  if (!raw)
    return null;
  try {
    const obj = JSON.parse(raw);
    if (!obj || typeof obj.base !== "string" || typeof obj.chosenAt !== "number")
      return null;
    if (deps.now() - obj.chosenAt > CACHE_TTL_MS)
      return null;
    if (!bases.includes(normalizeBase(obj.base)))
      return null;
    return obj;
  } catch {
    return null;
  }
};
var consecutiveFailures = 0;
var selectFastestBase = async (bases, deps = defaultDeps) => {
  const pool = bases.length ? bases.map(normalizeBase) : relaysToBases();
  const cached = readCache(pool, deps);
  if (cached) {
    log("\u{1F527} relaySelector \u547D\u4E2D\u7F13\u5B58:", cached.base);
    return cached.base;
  }
  const result = await raceProbe(pool, deps);
  if (result) {
    deps.storage.setItem(
      CACHE_KEY,
      JSON.stringify({
        base: result.base,
        latencyMs: result.latencyMs,
        chosenAt: deps.now()
      })
    );
    consecutiveFailures = 0;
    log("\u{1F527} relaySelector \u9009\u4E2D:", result.base, `${result.latencyMs}ms`);
    return result.base;
  }
  logError("relaySelector \u6240\u6709\u5019\u9009\u90FD\u5931\u8D25\uFF0C\u56DE\u9000:", pool[0]);
  return pool[0];
};
var getOrderedFallbackBases = async (bases, deps = defaultDeps) => {
  const pool = bases.length ? bases.map(normalizeBase) : relaysToBases();
  const primary = await selectFastestBase(pool, deps);
  const rest = pool.filter((b) => b !== primary);
  return [primary, ...rest];
};
var notifyRequestFailure = (deps = defaultDeps) => {
  consecutiveFailures += 1;
  if (consecutiveFailures >= FAILURE_THRESHOLD) {
    log("\u{1F527} relaySelector \u8FDE\u7EED\u5931\u8D25\u9608\u503C\u89E6\u53D1\uFF0C\u6E05\u7F13\u5B58");
    deps.storage.removeItem(CACHE_KEY);
    consecutiveFailures = 0;
  }
};
var notifyRequestSuccess = () => {
  consecutiveFailures = 0;
};
var clearRelayCache = (deps = defaultDeps) => {
  deps.storage.removeItem(CACHE_KEY);
  consecutiveFailures = 0;
};
var peekRelayCache = (deps = defaultDeps) => {
  const raw = deps.storage.getItem(CACHE_KEY);
  if (!raw)
    return null;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
};

// src/registry.ts
var CONFIG_PATH = "/plugin-market/marketplace-config.json";
var DEFAULT_OFFICIAL_INDEX_BASE = "/gh/raw/obsidianmd/obsidian-releases/HEAD";
var COMMUNITY_PLUGINS = "community-plugins.json";
var COMMUNITY_STATS = "community-plugin-stats.json";
var COMMUNITY_DEPRECATION = "community-plugin-deprecation.json";
var CATALOG_TTL_MS = 5 * 60 * 1e3;
var defaultNet = {
  async getJson(url) {
    const r = await (0, import_obsidian2.requestUrl)({
      url,
      method: "GET",
      headers: { "Content-Type": "application/json" }
    });
    return { status: r.status, json: r.json };
  }
};
var resolveUrl = (base, path) => {
  if (/^https?:\/\//i.test(path))
    return path;
  const b = base.replace(/\/+$/, "");
  const p = path.startsWith("/") ? path : "/" + path;
  return b + p;
};
var validateSpecialImport = (s) => {
  if (!s.id || !s.name)
    return { ok: false, reason: "missing id/name" };
  if (s.repo)
    return { ok: true };
  if (s.manifestUrl || s.assetBase) {
    if (s.manifestUrl && !isAllowedUrl(s.manifestUrl))
      return { ok: false, reason: "manifestUrl not whitelisted/https" };
    if (s.assetBase && !isAllowedUrl(s.assetBase))
      return { ok: false, reason: "assetBase not whitelisted/https" };
    if (!s.manifestUrl || !s.assetBase)
      return { ok: false, reason: "need both manifestUrl and assetBase" };
    return { ok: true };
  }
  return { ok: false, reason: "no repo nor manifestUrl/assetBase" };
};
var mergeCatalog = (official, stats, deprecation, config, opts) => {
  const blacklist = new Set(config.blacklist || []);
  const pinned = new Set(config.pinned || []);
  const byId = /* @__PURE__ */ new Map();
  for (const p of official) {
    if (!p || !p.id)
      continue;
    if (blacklist.has(p.id))
      continue;
    byId.set(p.id, {
      id: p.id,
      name: p.name,
      author: p.author,
      description: p.description,
      repo: p.repo,
      source: "official",
      downloads: stats[p.id]?.downloads,
      deprecated: Object.prototype.hasOwnProperty.call(deprecation, p.id),
      pinned: pinned.has(p.id)
    });
  }
  if (opts.enableSpecialImports) {
    for (const s of config.specialImports || []) {
      const v = validateSpecialImport(s);
      if (!v.ok) {
        logError("\u7279\u6B8A\u5BFC\u5165\u6761\u76EE\u65E0\u6548\uFF0C\u8DF3\u8FC7:", s.id, v.reason);
        continue;
      }
      byId.set(s.id, {
        id: s.id,
        name: s.name,
        author: s.author,
        description: s.description,
        repo: s.repo,
        source: "special",
        manifestUrl: s.manifestUrl,
        assetBase: s.assetBase,
        minAppVersion: s.minAppVersion,
        channel: s.channel,
        pinned: pinned.has(s.id)
      });
    }
  }
  const entries = Array.from(byId.values());
  entries.sort((a, b) => {
    if (!!a.pinned !== !!b.pinned)
      return a.pinned ? -1 : 1;
    const da = a.downloads ?? -1;
    const db = b.downloads ?? -1;
    if (da !== db)
      return db - da;
    return a.name.localeCompare(b.name);
  });
  return entries;
};
var FALLBACK_CONFIG = {
  version: 0,
  relays: [],
  blacklist: [],
  specialImports: []
};
var Registry = class {
  constructor(net = defaultNet) {
    this.cache = null;
    this.cachedAt = 0;
    /** 上一次配置里的 relays，给下一轮选节点用（服务端热加节点） */
    this.knownRelays = [];
    this.net = net;
  }
  getKnownRelays() {
    return this.knownRelays;
  }
  /** 逐 base 尝试取 JSON，首个 200 胜；全失败抛错 */
  async fetchFirst(bases, path) {
    let lastErr = null;
    for (const base of bases) {
      const url = resolveUrl(base, path);
      try {
        const r = await this.net.getJson(url);
        if (r.status === 200 && r.json != null) {
          notifyRequestSuccess();
          return r.json;
        }
        lastErr = new Error(`status=${r.status} @ ${url}`);
      } catch (e) {
        lastErr = e;
      }
    }
    notifyRequestFailure();
    throw lastErr || new Error("all bases failed for " + path);
  }
  async fetchConfig(bases, customConfigUrl) {
    if (customConfigUrl) {
      if (!isAllowedUrl(customConfigUrl)) {
        logError("\u81EA\u5B9A\u4E49 config URL \u975E\u767D\u540D\u5355\uFF0C\u5FFD\u7565:", customConfigUrl);
      } else {
        try {
          const r = await this.net.getJson(customConfigUrl);
          if (r.status === 200 && r.json)
            return r.json;
        } catch (e) {
          logError("\u81EA\u5B9A\u4E49 config URL \u53D6\u5931\u8D25\uFF0C\u56DE\u9000\u9ED8\u8BA4:", e);
        }
      }
    }
    const json = await this.fetchFirst(bases, CONFIG_PATH);
    return json;
  }
  /**
   * 拉取合并后的插件清单。force=true 跳过 5min 缓存。
   */
  async load(settings, force = false) {
    const now = Date.now();
    if (!force && this.cache && now - this.cachedAt < CATALOG_TTL_MS) {
      return this.cache;
    }
    const bootstrapBases = await getOrderedFallbackBases(
      relaysToBases(this.knownRelays)
    );
    let config;
    try {
      config = await this.fetchConfig(bootstrapBases, settings.customConfigUrl);
    } catch (e) {
      logError("\u53D6 marketplace-config \u5931\u8D25\uFF0C\u7528\u7A7A\u914D\u7F6E:", e);
      config = { ...FALLBACK_CONFIG };
    }
    if (Array.isArray(config.relays) && config.relays.length) {
      this.knownRelays = config.relays;
    }
    const bases = await getOrderedFallbackBases(relaysToBases(config.relays));
    const indexBase = config.officialIndex?.base || DEFAULT_OFFICIAL_INDEX_BASE;
    const idxPath = (file) => /^https?:\/\//i.test(indexBase) ? resolveUrl(indexBase, file) : indexBase.replace(/\/+$/, "") + "/" + file;
    const official = await this.fetchFirst(
      bases,
      idxPath(COMMUNITY_PLUGINS)
    ).catch((e) => {
      logError("\u53D6\u5B98\u65B9 community-plugins \u5931\u8D25:", e);
      return [];
    });
    const stats = await this.fetchFirst(bases, idxPath(COMMUNITY_STATS)).catch(
      () => ({})
    );
    const deprecation = await this.fetchFirst(
      bases,
      idxPath(COMMUNITY_DEPRECATION)
    ).catch(() => ({}));
    const entries = mergeCatalog(
      Array.isArray(official) ? official : [],
      stats || {},
      deprecation || {},
      config,
      { enableSpecialImports: settings.enableSpecialImports }
    );
    const result = {
      entries,
      config,
      base: bases[0]
    };
    this.cache = result;
    this.cachedAt = now;
    log("\u{1F4E6} registry \u5408\u5E76\u5B8C\u6210:", entries.length, "\u6761\uFF0Cbase=", bases[0]);
    return result;
  }
  invalidate() {
    this.cache = null;
    this.cachedAt = 0;
  }
};

// src/installer.ts
var RELEASE_FILES = {
  manifest: "manifest.json",
  main: "main.js",
  styles: "styles.css"
};
var releaseAssetUrl = (base, repo, version, file) => `${base.replace(/\/+$/, "")}/gh/release/${repo}/${version}/${file}`;
var rawHeadManifestUrl = (base, repo) => `${base.replace(/\/+$/, "")}/gh/raw/${repo}/HEAD/${RELEASE_FILES.manifest}`;
var pluginFolder = (configDir, id) => `${configDir.replace(/\/+$/, "")}/plugins/${id}`;
var getInstalledState = (id, plugins) => {
  const manifest = plugins.manifests[id];
  return {
    installed: !!manifest,
    enabled: plugins.enabledPlugins.has(id),
    version: manifest?.version
  };
};
var installEntry = async (entry, base, ctx) => {
  const { net, fs, plugins, configDir } = ctx;
  let manifestUrl;
  let mainUrl;
  let stylesUrl;
  const useDirect = entry.source === "special" && entry.manifestUrl && entry.assetBase;
  if (useDirect) {
    const assetBase = entry.assetBase.replace(/\/+$/, "") + "/";
    manifestUrl = entry.manifestUrl;
    mainUrl = assetBase + RELEASE_FILES.main;
    stylesUrl = assetBase + RELEASE_FILES.styles;
  } else {
    const repo = entry.repo;
    if (!repo)
      throw new Error(`\u63D2\u4EF6 ${entry.id} \u7F3A\u5C11 repo / \u76F4\u94FE\u4FE1\u606F\uFF0C\u65E0\u6CD5\u5B89\u88C5`);
    const headManifest = await fetchTextOk(net, rawHeadManifestUrl(base, repo));
    let headParsed;
    try {
      headParsed = JSON.parse(headManifest);
    } catch {
      throw new Error(`\u63D2\u4EF6 ${entry.id} \u7684 HEAD manifest \u4E0D\u662F\u5408\u6CD5 JSON`);
    }
    const version = headParsed.version;
    if (!version)
      throw new Error(`\u63D2\u4EF6 ${entry.id} HEAD manifest \u7F3A version`);
    manifestUrl = releaseAssetUrl(base, repo, version, RELEASE_FILES.manifest);
    mainUrl = releaseAssetUrl(base, repo, version, RELEASE_FILES.main);
    stylesUrl = releaseAssetUrl(base, repo, version, RELEASE_FILES.styles);
  }
  const manifestText = await fetchTextOk(net, manifestUrl);
  let manifest;
  try {
    manifest = JSON.parse(manifestText);
  } catch {
    throw new Error(`\u63D2\u4EF6 ${entry.id} \u7684 release manifest \u4E0D\u662F\u5408\u6CD5 JSON`);
  }
  if (manifest.id !== entry.id) {
    throw new Error(
      `\u63D2\u4EF6 id \u4E0D\u5339\u914D\uFF1A\u671F\u671B ${entry.id}\uFF0C\u5B9E\u9645 ${manifest.id}\uFF08\u62D2\u7EDD\u5B89\u88C5\uFF09`
    );
  }
  const mainText = await fetchTextOk(net, mainUrl);
  if (!mainText || mainText.length < 100) {
    throw new Error(`\u63D2\u4EF6 ${entry.id} \u7684 main.js \u5F02\u5E38\uFF08\u8FC7\u5C0F/\u4E3A\u7A7A\uFF09`);
  }
  let stylesText = null;
  try {
    stylesText = await fetchTextOk(net, stylesUrl);
  } catch {
    stylesText = null;
  }
  const folder = pluginFolder(configDir, entry.id);
  if (!await fs.exists(folder)) {
    await fs.mkdir(folder);
  }
  await fs.write(`${folder}/${RELEASE_FILES.manifest}`, manifestText);
  await fs.write(`${folder}/${RELEASE_FILES.main}`, mainText);
  if (stylesText != null) {
    await fs.write(`${folder}/${RELEASE_FILES.styles}`, stylesText);
  }
  await plugins.loadManifests();
  if (plugins.plugins[entry.id] || plugins.enabledPlugins.has(entry.id)) {
    try {
      await plugins.disablePlugin(entry.id);
    } catch {
    }
  }
  await plugins.enablePluginAndSave(entry.id);
  log("\u2705 \u5B89\u88C5\u5B8C\u6210:", entry.id, manifest.version, useDirect ? "(direct)" : "(repo)");
  return manifest.version;
};
var fetchTextOk = async (net, url) => {
  const r = await net.getText(url);
  if (r.status !== 200)
    throw new Error(`HTTP ${r.status} @ ${url}`);
  return r.text;
};

// src/deeplink.ts
var str = (v) => typeof v === "string" ? v.trim() : "";
var parseDeeplinkParams = (params) => {
  const op = str(params.op) || "open";
  if (op === "open")
    return { kind: "open" };
  if (op === "install") {
    const id = str(params.id);
    if (!id)
      return { kind: "reject", reason: "install \u7F3A\u5C11 id" };
    return { kind: "install", id };
  }
  if (op === "special-import" || op === "import") {
    const id = str(params.id);
    const manifestUrl = str(params.manifest || params.manifestUrl);
    const assetBase = str(params.assetBase || params.base);
    if (!id)
      return { kind: "reject", reason: "special-import \u7F3A\u5C11 id" };
    if (!manifestUrl || !assetBase)
      return { kind: "reject", reason: "special-import \u7F3A\u5C11 manifest/assetBase" };
    if (!isAllowedUrl(manifestUrl))
      return { kind: "reject", reason: `manifest \u975E\u767D\u540D\u5355\u57DF: ${manifestUrl}` };
    if (!isAllowedUrl(assetBase))
      return { kind: "reject", reason: `assetBase \u975E\u767D\u540D\u5355\u57DF: ${assetBase}` };
    const entry = {
      id,
      name: str(params.name) || id,
      author: str(params.author) || "\u672A\u77E5",
      description: str(params.description) || "\u901A\u8FC7\u8C03\u8D77\u94FE\u63A5\u5BFC\u5165",
      source: "special",
      manifestUrl,
      assetBase,
      minAppVersion: str(params.minAppVersion) || void 0,
      channel: "test"
    };
    return { kind: "special-import", entry };
  }
  return { kind: "reject", reason: `\u672A\u77E5 op: ${op}` };
};
var runDeeplink = async (params, ctx) => {
  if (!ctx.enabled) {
    ctx.notify("\u8C03\u8D77\u94FE\u63A5\u5DF2\u5728\u8BBE\u7F6E\u4E2D\u5173\u95ED");
    return;
  }
  const intent = parseDeeplinkParams(params);
  switch (intent.kind) {
    case "open":
      await ctx.openView();
      return;
    case "install": {
      await ctx.openView();
      ctx.locate(intent.id);
      const ok = await ctx.confirm(
        "\u5B89\u88C5\u63D2\u4EF6",
        `\u786E\u8BA4\u4ECE\u52A0\u901F\u5546\u5E97\u5B89\u88C5\u63D2\u4EF6\u300C${intent.id}\u300D\uFF1F`
      );
      if (ok)
        await ctx.installById(intent.id);
      return;
    }
    case "special-import": {
      await ctx.openView();
      const e = intent.entry;
      const ok = await ctx.confirm(
        "\u5BFC\u5165\u7B2C\u4E09\u65B9\u63D2\u4EF6",
        `\u5373\u5C06\u4ECE\u767D\u540D\u5355\u57DF\u5BFC\u5165\u63D2\u4EF6\u300C${e.name}\u300D(${e.id})
\u4F5C\u8005\uFF1A${e.author}
\u6765\u6E90\uFF1A${e.manifestUrl}

\u7B2C\u4E09\u65B9\u63D2\u4EF6\u4F1A\u8FD0\u884C\u5176\u81EA\u5E26\u4EE3\u7801\uFF0C\u786E\u8BA4\u4FE1\u4EFB\u5E76\u5B89\u88C5\uFF1F`
      );
      if (ok)
        await ctx.installEntry(e);
      return;
    }
    case "reject":
      ctx.notify(`\u8C03\u8D77\u94FE\u63A5\u88AB\u62D2\u7EDD\uFF1A${intent.reason}`);
      return;
  }
};

// src/confirmModal.ts
var import_obsidian3 = require("obsidian");
var ConfirmModal = class extends import_obsidian3.Modal {
  constructor(app, title, body, resolver) {
    super(app);
    this.resolved = false;
    this.title = title;
    this.body = body;
    this.resolver = resolver;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: this.title });
    for (const line of this.body.split("\n")) {
      contentEl.createEl("p", { text: line });
    }
    const btnRow = contentEl.createDiv({ cls: "modal-button-container" });
    const cancel = btnRow.createEl("button", { text: "\u53D6\u6D88" });
    cancel.onclick = () => {
      this.finish(false);
    };
    const ok = btnRow.createEl("button", { text: "\u786E\u8BA4", cls: "mod-cta" });
    ok.onclick = () => {
      this.finish(true);
    };
  }
  finish(v) {
    if (this.resolved)
      return;
    this.resolved = true;
    this.resolver(v);
    this.close();
  }
  onClose() {
    if (!this.resolved) {
      this.resolved = true;
      this.resolver(false);
    }
    this.contentEl.empty();
  }
};
var confirmDialog = (app, title, body) => new Promise((resolve) => {
  new ConfirmModal(app, title, body, resolve).open();
});

// src/marketView.ts
var import_obsidian4 = require("obsidian");
var MARKET_VIEW_TYPE = "plugin-market-cn-view";
var MarketView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.entries = [];
    this.filterText = "";
    this.activeTab = "all";
    this.loading = false;
    this.plugin = plugin;
  }
  getViewType() {
    return MARKET_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u63D2\u4EF6\u52A0\u901F\u5546\u5E97";
  }
  getIcon() {
    return "store";
  }
  async onOpen() {
    const root = this.contentEl;
    root.empty();
    root.addClass("pmcn-view");
    this.buildToolbar(root);
    this.listEl = root.createDiv({ cls: "pmcn-list" });
    await this.reloadCatalog(false);
  }
  buildToolbar(root) {
    const toolbar = root.createDiv({ cls: "pmcn-toolbar" });
    const row1 = toolbar.createDiv({ cls: "pmcn-toolbar-row" });
    const search = row1.createEl("input", {
      cls: "pmcn-search",
      attr: { type: "text", placeholder: "\u641C\u7D22\u63D2\u4EF6\u540D / \u4F5C\u8005 / \u63CF\u8FF0\u2026" }
    });
    search.addEventListener("input", () => {
      this.filterText = search.value.trim().toLowerCase();
      this.renderList();
    });
    const refreshBtn = row1.createEl("button", { text: "\u5237\u65B0" });
    refreshBtn.addEventListener("click", () => void this.reloadCatalog(true));
    const row2 = toolbar.createDiv({ cls: "pmcn-toolbar-row" });
    this.tabsEl = row2.createDiv({ cls: "pmcn-tabs" });
    this.buildTabs();
    this.nodeStatusEl = row2.createDiv({ cls: "pmcn-node-status" });
    this.renderNodeStatus(false);
  }
  buildTabs() {
    this.tabsEl.empty();
    const tabs = [
      { key: "all", label: "\u5168\u90E8" },
      { key: "installed", label: "\u5DF2\u5B89\u88C5" },
      { key: "special", label: "\u7279\u6B8A\u5BFC\u5165" }
    ];
    for (const t of tabs) {
      const el = this.tabsEl.createDiv({
        cls: "pmcn-tab" + (this.activeTab === t.key ? " is-active" : ""),
        text: t.label
      });
      el.addEventListener("click", () => {
        this.activeTab = t.key;
        this.buildTabs();
        this.renderList();
      });
    }
  }
  renderNodeStatus(ok) {
    this.nodeStatusEl.empty();
    this.nodeStatusEl.createSpan({
      cls: "pmcn-node-dot" + (ok ? " is-ok" : "")
    });
    this.nodeStatusEl.createSpan({
      text: ok ? "\u52A0\u901F\u5DF2\u8FDE\u63A5" : "\u8FDE\u63A5\u52A0\u901F\u7EBF\u8DEF\u2026"
    });
  }
  async reloadCatalog(force) {
    if (this.loading)
      return;
    this.loading = true;
    this.listEl.empty();
    this.listEl.createDiv({ cls: "pmcn-empty", text: "\u6B63\u5728\u52A0\u8F7D\u6E05\u5355\u2026" });
    try {
      const result = await this.plugin.registry.load(this.plugin.settings, force);
      this.entries = result.entries;
      this.renderNodeStatus(true);
      this.renderList();
    } catch (e) {
      logError("\u52A0\u8F7D\u6E05\u5355\u5931\u8D25:", e);
      this.listEl.empty();
      this.listEl.createDiv({
        cls: "pmcn-empty",
        text: `\u52A0\u8F7D\u5931\u8D25\uFF1A${e instanceof Error ? e.message : e}`
      });
    } finally {
      this.loading = false;
    }
  }
  /** 供外部（如调起链接安装后）刷新按钮态 */
  refresh() {
    this.renderList();
  }
  /** 定位某个 id：设为搜索词并切到全部 */
  locate(id) {
    this.activeTab = "all";
    this.filterText = id.toLowerCase();
    this.buildTabs();
    this.renderList();
  }
  visibleEntries() {
    return this.entries.filter((e) => {
      if (this.activeTab === "special" && e.source !== "special")
        return false;
      if (this.activeTab === "installed") {
        if (!this.plugin.getInstalledState(e.id).installed)
          return false;
      }
      if (this.filterText) {
        const hay = (e.id + " " + e.name + " " + e.author + " " + e.description).toLowerCase();
        if (!hay.includes(this.filterText))
          return false;
      }
      return true;
    });
  }
  renderList() {
    this.listEl.empty();
    const items = this.visibleEntries();
    if (items.length === 0) {
      this.listEl.createDiv({ cls: "pmcn-empty", text: "\u6CA1\u6709\u5339\u914D\u7684\u63D2\u4EF6" });
      return;
    }
    const MAX = 300;
    for (const entry of items.slice(0, MAX)) {
      this.renderCard(entry);
    }
    if (items.length > MAX) {
      this.listEl.createDiv({
        cls: "pmcn-empty",
        text: `\u4EC5\u663E\u793A\u524D ${MAX} / ${items.length} \u6761\uFF0C\u8BF7\u7528\u641C\u7D22\u7F29\u5C0F\u8303\u56F4`
      });
    }
  }
  renderCard(entry) {
    const card = this.listEl.createDiv({ cls: "pmcn-card" });
    const title = card.createDiv({ cls: "pmcn-card-title" });
    title.createSpan({ text: entry.name });
    if (entry.source === "special") {
      title.createSpan({ cls: "pmcn-badge is-special", text: "\u7279\u6B8A\u5BFC\u5165" });
    }
    if (entry.deprecated) {
      title.createSpan({ cls: "pmcn-badge is-deprecated", text: "\u5DF2\u5F03\u7528" });
    }
    if (entry.pinned) {
      title.createSpan({ cls: "pmcn-badge", text: "\u7F6E\u9876" });
    }
    card.createDiv({ cls: "pmcn-card-author", text: `\u4F5C\u8005\uFF1A${entry.author}` });
    card.createDiv({ cls: "pmcn-card-desc", text: entry.description });
    const footer = card.createDiv({ cls: "pmcn-card-footer" });
    footer.createSpan({
      cls: "pmcn-downloads",
      text: entry.downloads != null ? `\u2193 ${entry.downloads.toLocaleString()}` : entry.source === "special" ? "\u7B2C\u4E09\u65B9" : ""
    });
    const state = this.plugin.getInstalledState(entry.id);
    const btn = footer.createEl("button");
    if (state.installed) {
      btn.setText(state.enabled ? "\u91CD\u65B0\u5B89\u88C5" : "\u5DF2\u5B89\u88C5\xB7\u542F\u7528");
    } else {
      btn.setText("\u5B89\u88C5");
      btn.addClass("mod-cta");
    }
    btn.addEventListener("click", async () => {
      btn.disabled = true;
      btn.setText("\u5B89\u88C5\u4E2D\u2026");
      await this.plugin.installMarketEntry(entry);
      btn.disabled = false;
      this.renderList();
    });
  }
};

// src/settingsTab.ts
var import_obsidian5 = require("obsidian");
var PluginMarketSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u63D2\u4EF6\u52A0\u901F\u5546\u5E97" });
    new import_obsidian5.Setting(containerEl).setName("\u52A0\u901F\u7EBF\u8DEF").setDesc("\u81EA\u52A8\u9009\u62E9\u6700\u5FEB\u52A0\u901F\u7EBF\u8DEF").addButton(
      (btn) => btn.setButtonText("\u91CD\u65B0\u6D4B\u901F").onClick(async () => {
        btn.setDisabled(true);
        await this.plugin.reprobeNodes();
        new import_obsidian5.Notice("\u5DF2\u91CD\u65B0\u6D4B\u901F\uFF0C\u5DF2\u5207\u6362\u5230\u6700\u5FEB\u7EBF\u8DEF");
        btn.setDisabled(false);
        this.display();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("\u542F\u7528\u7279\u6B8A\u5BFC\u5165").setDesc("\u5C55\u793A\u5E76\u5141\u8BB8\u5B89\u88C5\u670D\u52A1\u7AEF\u914D\u7F6E\u6CE8\u5165\u7684\u975E\u5B98\u65B9\u63D2\u4EF6").addToggle(
      (t) => t.setValue(this.plugin.settings.enableSpecialImports).onChange(async (v) => {
        this.plugin.settings.enableSpecialImports = v;
        this.plugin.registry.invalidate();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("\u542F\u7528\u8C03\u8D77\u94FE\u63A5").setDesc(
      "\u5141\u8BB8\u5B98\u7F51\uFF08\u4EA7\u54C1\u81EA\u6709\u767D\u540D\u5355\u57DF\uFF09\u901A\u8FC7 obsidian://plugin-market-cn \u94FE\u63A5\u6253\u5F00\u5546\u5E97 / \u5B89\u88C5\u63D2\u4EF6"
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.enableDeeplink).onChange(async (v) => {
        this.plugin.settings.enableDeeplink = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("\u542F\u7528\u63D2\u4EF6\u81EA\u66F4\u65B0").setDesc("\u542F\u52A8\u65F6\u68C0\u67E5\u672C\u63D2\u4EF6\u65B0\u7248\u672C\uFF0C\u786E\u8BA4\u540E\u4E0B\u8F7D\u5E76\u539F\u5B50\u66FF\u6362").addToggle(
      (t) => t.setValue(this.plugin.settings.enableSelfUpdate).onChange(async (v) => {
        this.plugin.settings.enableSelfUpdate = v;
        await this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText("\u7ACB\u5373\u68C0\u67E5").onClick(() => {
        void this.plugin.runSelfUpdateCheck(true);
      })
    );
    new import_obsidian5.Setting(containerEl).setName("\u81EA\u5B9A\u4E49\u6E05\u5355\u5730\u5740\uFF08\u9AD8\u7EA7\uFF09").setDesc(
      "\u8986\u76D6 marketplace-config.json \u6765\u6E90\uFF1B\u5FC5\u987B\u662F\u4EA7\u54C1\u81EA\u6709\u767D\u540D\u5355\u57DF https \u94FE\u63A5\uFF0C\u7559\u7A7A\u7528\u9ED8\u8BA4"
    ).addText(
      (txt) => txt.setPlaceholder("https://\u2026/marketplace-config.json").setValue(this.plugin.settings.customConfigUrl).onChange(async (v) => {
        const val = v.trim();
        if (val && !isAllowedUrl(val)) {
          txt.inputEl.style.borderColor = "var(--color-red)";
        } else {
          txt.inputEl.style.borderColor = "";
        }
        this.plugin.settings.customConfigUrl = val;
        this.plugin.registry.invalidate();
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/updater/types.ts
var PLUGIN_MARKET_PATH = "/plugin-market";
var VERSION_FILE = "version.json";
var SELF_UPDATE_FILES = ["manifest.json", "main.js", "styles.css"];
var TEMP_SUFFIX = ".update-temp";
var VERSION_CHECK_DEBOUNCE_MS = 60 * 1e3;
var MIN_MAIN_JS_SIZE = 1e3;

// src/updater/PluginUpdater.ts
var join = (base, file) => `${base.replace(/\/+$/, "")}${PLUGIN_MARKET_PATH}/${file}`;
var PluginUpdater = class {
  constructor(deps, pluginDir, currentVersion) {
    this.lastCheckTime = 0;
    this.cached = null;
    this.isUpdating = false;
    this.deps = deps;
    this.pluginDir = pluginDir;
    this.currentVersion = currentVersion;
  }
  /** 逐 base 取某文件文本，首个 200 胜 */
  async fetchAcrossBases(file) {
    const bases = await this.deps.basesProvider();
    let lastErr = null;
    for (const base of bases) {
      try {
        const r = await this.deps.requestText(join(base, file));
        if (r.status === 200)
          return { text: r.text, json: r.json };
        lastErr = new Error(`HTTP ${r.status}`);
      } catch (e) {
        lastErr = e;
      }
    }
    throw lastErr || new Error("all bases failed for " + file);
  }
  async checkForUpdate(forceCheck = false) {
    const now = this.deps.now();
    if (!forceCheck && this.cached && now - this.lastCheckTime < VERSION_CHECK_DEBOUNCE_MS) {
      return this.buildResult(this.cached);
    }
    try {
      const { text, json } = await this.fetchAcrossBases(VERSION_FILE);
      const data = json ?? JSON.parse(text);
      if (!data || typeof data.version !== "string") {
        throw new Error("version.json \u7F3A version \u5B57\u6BB5");
      }
      this.cached = { version: data.version };
      this.lastCheckTime = now;
      return this.buildResult(this.cached);
    } catch (error) {
      logError("\u{1F504} [updater] \u7248\u672C\u68C0\u67E5\u5931\u8D25:", error);
      return {
        hasUpdate: false,
        currentVersion: this.currentVersion,
        latestVersion: "",
        error: error instanceof Error ? error.message : "version check failed"
      };
    }
  }
  buildResult(info) {
    return {
      hasUpdate: isNewerVersion(info.version, this.currentVersion),
      currentVersion: this.currentVersion,
      latestVersion: info.version
    };
  }
  async performUpdate() {
    if (this.isUpdating) {
      return { success: false, message: "\u66F4\u65B0\u6B63\u5728\u8FDB\u884C\u4E2D\uFF0C\u8BF7\u7A0D\u5019" };
    }
    this.isUpdating = true;
    const updated = [];
    try {
      const downloaded = {};
      for (const file of SELF_UPDATE_FILES) {
        try {
          const { text } = await this.fetchAcrossBases(file);
          downloaded[file] = text;
        } catch (e) {
          if (file === "styles.css") {
            log("\u{1F504} [updater] styles.css \u7F3A\u5931\uFF0C\u8DF3\u8FC7");
            continue;
          }
          throw e;
        }
      }
      if (!downloaded["main.js"] || downloaded["main.js"].length < MIN_MAIN_JS_SIZE) {
        throw new Error("main.js \u5F02\u5E38\uFF08\u8FC7\u5C0F/\u4E3A\u7A7A\uFF09");
      }
      if (!downloaded["manifest.json"]) {
        throw new Error("manifest.json \u7F3A\u5931");
      }
      try {
        JSON.parse(downloaded["manifest.json"]);
      } catch {
        throw new Error("manifest.json \u4E0D\u662F\u5408\u6CD5 JSON");
      }
      for (const file of Object.keys(downloaded)) {
        await this.deps.adapter.write(
          `${this.pluginDir}/${file}${TEMP_SUFFIX}`,
          downloaded[file]
        );
      }
      for (const file of Object.keys(downloaded)) {
        const target = `${this.pluginDir}/${file}`;
        if (await this.deps.adapter.exists(target)) {
          const orig = await this.deps.adapter.read(target);
          await this.deps.adapter.write(`${target}.backup`, orig);
        }
        await this.deps.adapter.write(target, downloaded[file]);
        updated.push(file);
      }
      await this.cleanupTemp();
      return {
        success: true,
        message: "\u63D2\u4EF6\u66F4\u65B0\u6210\u529F\uFF01\u8BF7\u91CD\u542F Obsidian \u4EE5\u5E94\u7528\u66F4\u65B0\u3002",
        filesUpdated: updated
      };
    } catch (error) {
      logError("\u{1F504} [updater] \u66F4\u65B0\u5931\u8D25:", error);
      await this.cleanupTemp();
      return {
        success: false,
        message: "\u66F4\u65B0\u5931\u8D25",
        error: error instanceof Error ? error.message : "Unknown error"
      };
    } finally {
      this.isUpdating = false;
    }
  }
  async cleanupTemp() {
    for (const file of SELF_UPDATE_FILES) {
      const tmp = `${this.pluginDir}/${file}${TEMP_SUFFIX}`;
      try {
        if (await this.deps.adapter.exists(tmp)) {
          await this.deps.adapter.remove(tmp);
        }
      } catch (e) {
        logError("\u{1F504} [updater] \u6E05\u7406\u4E34\u65F6\u6587\u4EF6\u5931\u8D25:", tmp, e);
      }
    }
  }
  isUpdateInProgress() {
    return this.isUpdating;
  }
};
var isNewerVersion = (latest, current) => {
  const parse = (v) => v.split(/[.\-+]/).map((n) => parseInt(n, 10) || 0);
  const L = parse(latest);
  const C = parse(current);
  for (let i = 0; i < Math.max(L.length, C.length); i++) {
    const l = L[i] || 0;
    const c = C[i] || 0;
    if (l > c)
      return true;
    if (l < c)
      return false;
  }
  return false;
};

// src/main.ts
var PROTOCOL_ACTION = "plugin-market-cn";
var PluginMarketPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.registry = new Registry();
    this.updater = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      MARKET_VIEW_TYPE,
      (leaf) => new MarketView(leaf, this)
    );
    this.addRibbonIcon("store", "\u63D2\u4EF6\u52A0\u901F\u5546\u5E97", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-plugin-market",
      name: "\u6253\u5F00\u63D2\u4EF6\u52A0\u901F\u5546\u5E97",
      callback: () => void this.activateView()
    });
    this.addCommand({
      id: "check-self-update",
      name: "\u68C0\u67E5\u63D2\u4EF6\u52A0\u901F\u5546\u5E97\u66F4\u65B0",
      callback: () => void this.runSelfUpdateCheck(true)
    });
    this.addSettingTab(new PluginMarketSettingTab(this.app, this));
    this.registerObsidianProtocolHandler(
      PROTOCOL_ACTION,
      (params) => {
        void this.handleProtocol(params);
      }
    );
    if (BUILD_CONFIG.ENABLE_AUTO_UPDATE && this.settings.enableSelfUpdate) {
      this.app.workspace.onLayoutReady(() => {
        void this.runSelfUpdateCheck(false);
      });
    }
    log("\u63D2\u4EF6\u52A0\u901F\u5546\u5E97\u5DF2\u52A0\u8F7D");
  }
  onunload() {
  }
  // ---------- 设置 ----------
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ---------- 视图 ----------
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const existing = workspace.getLeavesOfType(MARKET_VIEW_TYPE);
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = workspace.getLeaf("tab");
      await leaf.setViewState({ type: MARKET_VIEW_TYPE, active: true });
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
  getMarketView() {
    const leaves = this.app.workspace.getLeavesOfType(MARKET_VIEW_TYPE);
    const view = leaves[0]?.view;
    return view instanceof MarketView ? view : null;
  }
  // ---------- relay base ----------
  async getOrderedBases() {
    return getOrderedFallbackBases(relaysToBases(this.registry.getKnownRelays()));
  }
  async getFastestBase() {
    const base = await selectFastestBase(
      relaysToBases(this.registry.getKnownRelays())
    );
    this.settings.lastFastestBase = base;
    return base;
  }
  currentBaseLabel() {
    const cache = peekRelayCache();
    return cache?.base || this.settings.lastFastestBase || "(\u672A\u6D4B\u901F)";
  }
  async reprobeNodes() {
    clearRelayCache();
    return this.getFastestBase();
  }
  // ---------- 安装 ----------
  get pluginsApi() {
    return this.app.plugins;
  }
  buildInstallContext() {
    const adapter = this.app.vault.adapter;
    return {
      net: {
        async getText(url) {
          const r = await (0, import_obsidian6.requestUrl)({ url, method: "GET" });
          return { status: r.status, text: r.text };
        }
      },
      fs: {
        exists: (p) => adapter.exists(p),
        mkdir: (p) => adapter.mkdir(p),
        write: (p, d) => adapter.write(p, d)
      },
      plugins: this.pluginsApi,
      configDir: this.app.vault.configDir
    };
  }
  getInstalledState(id) {
    return getInstalledState(id, this.pluginsApi);
  }
  async installMarketEntry(entry) {
    const notice = new import_obsidian6.Notice(`\u6B63\u5728\u5B89\u88C5\u300C${entry.name}\u300D\u2026`, 0);
    try {
      const base = await this.getFastestBase();
      const version = await installEntry(entry, base, this.buildInstallContext());
      notice.setMessage(`\u300C${entry.name}\u300D\u5B89\u88C5\u6210\u529F v${version}`);
      setTimeout(() => notice.hide(), 4e3);
      this.getMarketView()?.refresh();
    } catch (e) {
      logError("\u5B89\u88C5\u5931\u8D25:", e);
      notice.setMessage(
        `\u300C${entry.name}\u300D\u5B89\u88C5\u5931\u8D25\uFF1A${e instanceof Error ? e.message : e}`
      );
      setTimeout(() => notice.hide(), 6e3);
    }
  }
  async installById(id) {
    try {
      const { entries } = await this.registry.load(this.settings);
      const entry = entries.find((e) => e.id === id);
      if (!entry) {
        new import_obsidian6.Notice(`\u5546\u5E97\u6E05\u5355\u91CC\u627E\u4E0D\u5230\u63D2\u4EF6\u300C${id}\u300D`);
        return;
      }
      await this.installMarketEntry(entry);
    } catch (e) {
      logError("installById \u5931\u8D25:", e);
      new import_obsidian6.Notice(`\u5B89\u88C5\u300C${id}\u300D\u5931\u8D25\uFF1A${e instanceof Error ? e.message : e}`);
    }
  }
  // ---------- 调起链接 ----------
  async handleProtocol(params) {
    await runDeeplink(params, {
      enabled: this.settings.enableDeeplink,
      openView: () => this.activateView(),
      locate: (id) => this.getMarketView()?.locate(id),
      confirm: (title, body) => confirmDialog(this.app, title, body),
      installById: (id) => this.installById(id),
      installEntry: (entry) => this.installMarketEntry(entry),
      notify: (msg) => new import_obsidian6.Notice(msg)
    });
  }
  // ---------- 自更新 ----------
  buildUpdater() {
    const adapter = this.app.vault.adapter;
    return new PluginUpdater(
      {
        requestText: async (url) => {
          const r = await (0, import_obsidian6.requestUrl)({ url, method: "GET" });
          return { status: r.status, text: r.text, json: r.json };
        },
        adapter: {
          write: (p, d) => adapter.write(p, d),
          read: (p) => adapter.read(p),
          exists: (p) => adapter.exists(p),
          remove: (p) => adapter.remove(p),
          stat: (p) => adapter.stat(p)
        },
        basesProvider: () => this.getOrderedBases(),
        now: () => Date.now()
      },
      `${this.app.vault.configDir}/plugins/${this.manifest.id}`,
      this.manifest.version
    );
  }
  async runSelfUpdateCheck(manual) {
    if (!BUILD_CONFIG.ENABLE_AUTO_UPDATE) {
      if (manual)
        new import_obsidian6.Notice("\u6B64\u6784\u5EFA\u672A\u5F00\u542F\u81EA\u66F4\u65B0");
      return;
    }
    if (!this.updater)
      this.updater = this.buildUpdater();
    const result = await this.updater.checkForUpdate(manual);
    if (result.error) {
      if (manual)
        new import_obsidian6.Notice(`\u68C0\u67E5\u66F4\u65B0\u5931\u8D25\uFF1A${result.error}`);
      return;
    }
    if (!result.hasUpdate) {
      if (manual)
        new import_obsidian6.Notice(`\u5DF2\u662F\u6700\u65B0\u7248\u672C v${result.currentVersion}`);
      return;
    }
    const ok = await confirmDialog(
      this.app,
      "\u53D1\u73B0\u65B0\u7248\u672C",
      `\u63D2\u4EF6\u52A0\u901F\u5546\u5E97\u6709\u65B0\u7248\u672C v${result.latestVersion}\uFF08\u5F53\u524D v${result.currentVersion}\uFF09\u3002
\u662F\u5426\u73B0\u5728\u66F4\u65B0\uFF1F\u66F4\u65B0\u540E\u9700\u91CD\u542F Obsidian\u3002`
    );
    if (!ok)
      return;
    const upd = await this.updater.performUpdate();
    new import_obsidian6.Notice(upd.message, upd.success ? 6e3 : 8e3);
  }
};

/* nosourcemap */